---@meta mods.repr

---
---Render Lua values as readable source-like text.
---
---## Usage
---
---```lua
---local repr = require("mods").repr
---
---local t = {
---  "first",
---  "second",
---  name = "Ada",
---  ok = true,
---  nested = { value = 42 },
---}
---
---print(repr(t))
-----> {
----->   [1] = "first",
----->   [2] = "second",
----->   name = "Ada",
----->   nested = {
----->     value = 42
----->   },
----->   ok = true
-----> }
---```
---
---### Key formatting
---
---Strings are quoted and reserved keys use bracket notation.
---
---```lua
---print(repr({ name = "Ada", ["with space"] = true }))
-----> {
----->   ["with space"] = true,
----->   name = "Ada"
-----> }
---```
---
---### Cycle rendering
---
---Circular references render as `<cycle>`.
---
---```lua
---local t = {}
---t.self = t
---
---print(repr(t))
-----> {
----->   self = <cycle>
-----> }
---```
---
---## Replacers
---
---A replacer can transform or remove values during rendering.
---
---```lua
---local function replacer(k, v)
---  if k ~= "secret" then
---    return v
---  end
---end
---
---print(repr({ name = "Ada", secret = "hidden" }, replacer))
-----> {
----->   name = "Ada"
-----> }
---```
---
---## Spacing
---
---`space` controls indentation: `nil` uses the default two-space indent, a
---positive number uses that many spaces up to 10, `0` or less produces inline
---output, a string uses that string up to 10 characters, and `""` also
---produces inline output.
---
---@param value any Lua value to render.
---@param replacer? fun(k:any, v:any):result:any Optional function that can transform or remove entries.
---@param space? integer|string Custom table indentation.
---@return string out Readable string representation.
---@nodiscard
local function repr(value, replacer, space) end

return repr
