---@meta _

---
---Lua runtime metadata and version compatibility flags.
---
---## Usage
---
---```lua
---runtime = mods.runtime
---
---print(runtime.version)  --> 501 | 502 | 503 | 504 | 505
---```
---
---@class mods.runtime
---
---Numeric version encoded as `major * 100 + minor`.
---
---```lua
---print(runtime.version) --> 501 | 502 | 503 | 504 | 505
---```
---
---@field version 501|502|503|504|505
---
---Major version number parsed from `version`.
---
---```lua
---print(runtime.major) --> 5
---```
---
---@field major 5
---
---Minor version number parsed from `version`.
---
---```lua
---print(runtime.minor) --> 1 | 2 | 3 | 4 | 5
---```
---
---@field minor 1|2|3|4|5
---
---True when running under LuaJIT.
---
---```lua
---print(runtime.is_luajit) --> true | false
---```
---
---@field is_luajit boolean
---
---
---True when running on a Windows host.
---
---```lua
---print(runtime.is_windows) --> true | false
---```
---
---@field is_windows boolean
---
---True when running on a Unix-like host (Linux, macOS).
---
---```lua
---print(runtime.is_unix) --> true | false
---```
---
---@field is_unix boolean
---
local M = {}

return M
